In [2]:
import pandas as pd
import numpy as np


all_data = pd.read_excel("./all_data2.xlsx")
all_data.head()

Unnamed: 0       Time name       lon         lat    band  pixel  cloud  \
0           0 2017-03-25  姉川沖  35.38681  136.212837  B1.TIF  10118      0   
1           1 2017-03-25  姉川沖  35.38681  136.212837  B2.TIF   9102      0   
2           2 2017-03-25  姉川沖  35.38681  136.212837  B3.TIF   7809      0   
3           3 2017-03-25  姉川沖  35.38681  136.212837  B4.TIF   7083      0   
4           4 2017-03-25  姉川沖  35.38681  136.212837  B5.TIF   6610      0   

   terrian  cloudconfidence  cloudshade  CH_value  
0        0                1           3  5.042857  
1        0                1           3  5.042857  
2        0                1           3  5.042857  
3        0                1           3  5.042857  
4        0                1           3  5.042857

In [3]:
all_data.dtypes

Unnamed: 0                  int64
Time               datetime64[ns]
name                       object
lon                       float64
lat                       float64
band                       object
pixel                       int64
cloud                       int64
terrian                     int64
cloudconfidence             int64
cloudshade                  int64
CH_value                  float64
dtype: object

In [4]:
all_data.isnull().sum()

Unnamed: 0          0
Time                0
name                0
lon                 0
lat                 0
band                0
pixel               0
cloud               0
terrian             0
cloudconfidence     0
cloudshade          0
CH_value           22
dtype: int64

In [5]:
all_data.shape

(12583, 12)

In [6]:
all_data_2 = all_data.dropna()

In [7]:
all_data_2.shape

(12561, 12)

In [8]:
all_data_2.isnull().sum()

Unnamed: 0         0
Time               0
name               0
lon                0
lat                0
band               0
pixel              0
cloud              0
terrian            0
cloudconfidence    0
cloudshade         0
CH_value           0
dtype: int64

In [11]:
time = []
time = all_data_2["Time"].unique()
print(time)

['2017-03-25T00:00:00.000000000' '2017-03-09T00:00:00.000000000'
 '2017-05-12T00:00:00.000000000' '2017-05-28T00:00:00.000000000'
 '2017-06-13T00:00:00.000000000' '2017-06-29T00:00:00.000000000'
 '2017-07-15T00:00:00.000000000' '2017-07-31T00:00:00.000000000'
 '2017-08-16T00:00:00.000000000' '2017-09-01T00:00:00.000000000'
 '2017-11-04T00:00:00.000000000' '2017-11-20T00:00:00.000000000'
 '2017-12-06T00:00:00.000000000' '2017-12-22T00:00:00.000000000'
 '2018-01-07T00:00:00.000000000' '2018-01-23T00:00:00.000000000'
 '2018-02-08T00:00:00.000000000' '2018-02-24T00:00:00.000000000'
 '2018-03-12T00:00:00.000000000' '2018-03-28T00:00:00.000000000'
 '2018-04-13T00:00:00.000000000' '2018-04-29T00:00:00.000000000'
 '2018-05-15T00:00:00.000000000' '2018-06-16T00:00:00.000000000'
 '2018-07-02T00:00:00.000000000' '2018-07-18T00:00:00.000000000'
 '2018-08-03T00:00:00.000000000' '2018-08-19T00:00:00.000000000'
 '2018-09-04T00:00:00.000000000' '2018-10-06T00:00:00.000000000'
 '2018-10-22T00:00:00.000

In [12]:
kyoten = []
kyoten = all_data_2["name"].unique()
kyoten

array(['姉川沖', '天野川沖', '彦根港沖', '蓮菜沖', '日の川沖', '大宮川沖', '大宮川沖中央', '知内川沖'],
      dtype=object)

In [13]:
np.unique(all_data_2["band"],return_counts = True)

(array(['B1.TIF', 'B10.TIF', 'B11.TIF', 'B2.TIF', 'B3.TIF', 'B4.TIF',
        'B5.TIF', 'B6.TIF', 'B7.TIF', 'B8.TIF', 'B9.TIF'], dtype=object),
 array([1141, 1142, 1142, 1142, 1142, 1142, 1142, 1142, 1142, 1142, 1142],
       dtype=int64))

In [162]:
list = []
pixel = []
CH = []
C_t_CC_CS = []
for t in time:
    for n in kyoten:
        pixel = all_data_2["pixel"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        CH = all_data_2["CH_value"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        C_t_CC_CS = all_data_2[["cloud","terrian","cloudconfidence","cloudshade"]][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        #print(CH1)
        if len(CH) != 0:
            list += [[t,n,pixel,C_t_CC_CS[0],CH[0]]]
    
#print(list)   

#array = np.array(list)
#rray
array7 = np.array(list)
array7

array([[numpy.datetime64('2017-03-25T00:00:00.000000000'), '姉川沖',
        array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        array([0, 0, 1, 3], dtype=int64), 5.042857142857143],
       [numpy.datetime64('2017-03-25T00:00:00.000000000'), '天野川沖',
        array([11505, 10443,  9137,  8595,  8440,  6879,  6622,  8891,  5832,
       18872, 18048], dtype=int64),
        array([1, 0, 3, 1], dtype=int64), 5.385714285714286],
       [numpy.datetime64('2017-03-25T00:00:00.000000000'), '彦根港沖',
        array([11487, 10326,  9673,  8788,  8332,  7186,  6848,  8808,  5877,
       18721, 17630], dtype=int64),
        array([1, 0, 3, 1], dtype=int64), 6.457142857142857],
       ...,
       [numpy.datetime64('2017-02-14T00:00:00.000000000'), '大宮川沖',
        array([16478, 15578, 13855, 13575, 13946, 10502,  9527, 13877,  5074,
       16827, 16272], dtype=int64),
        array([1, 0, 3, 1], dtype=int64), 5.2],
       [numpy.datetime64('2017-

In [163]:
#np.savetxt("./data_array_success.txt",array7,fmt = "%s")

In [38]:
all_data_2[(all_data_2["name"]== "知内川") & (all_data_2["Time"] == pd.to_datetime(str(20170214)))]["cloud"].values

array([], dtype=int64)

In [42]:
all_data_2[(all_data_2["Time"]== pd.to_datetime(str(20170325))) & (all_data_2["name"] == "姉川沖")][["cloud","terrian","cloudconfidence","cloudshade"]].values

array([[0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3],
       [0, 0, 1, 3]], dtype=int64)

In [164]:
list2 = []
list3 = []
list4 = []
pixel2 = []
CH2 = []
Cloud = []
terrian = []
CC = []
CS = []
for t in time:
    for n in kyoten:
        pixel2 = all_data_2["pixel"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        CH2 = all_data_2["CH_value"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        Cloud= all_data_2["cloud"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        terrian = all_data_2["terrian"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        CC = all_data_2["cloudconfidence"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        CS = all_data_2["cloudshade"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        #print(CH1)
        if len(CH2) != 0:
            list2 += [[pixel2,Cloud[0],terrian[0],CC[0], CS[0],CH2[0]]]
            list3 += [[pixel,Cloud[0],terrian[0],CC[0],CS[0]]]
            list4 += [[CH2[0]]]
    
#print(list)   

#array = np.array(list)
#rray
array8 = np.array(list2)
array8

array([[array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        0, 0, 1, 3, 5.042857142857143],
       [array([11505, 10443,  9137,  8595,  8440,  6879,  6622,  8891,  5832,
       18872, 18048], dtype=int64),
        1, 0, 3, 1, 5.385714285714286],
       [array([11487, 10326,  9673,  8788,  8332,  7186,  6848,  8808,  5877,
       18721, 17630], dtype=int64),
        1, 0, 3, 1, 6.457142857142857],
       ...,
       [array([16478, 15578, 13855, 13575, 13946, 10502,  9527, 13877,  5074,
       16827, 16272], dtype=int64),
        1, 0, 3, 1, 5.2],
       [array([25701, 25632, 24003, 24956, 26335, 19614, 16795, 24580,  5217,
       15364, 15132], dtype=int64),
        1, 0, 3, 1, 5.6],
       [array([20972, 20387, 18497, 18713, 19180, 13451, 11020, 18902,  5074,
       17418, 16833], dtype=int64),
        1, 0, 3, 1, 6.666666666666666]], dtype=object)

In [104]:
array8.shape

(1134, 6)

In [146]:
np.savetxt("./data_array_honbanyou.txt",array8,fmt = "%s")

In [148]:
data_array = np.array(list3)
CH_array = np.array(list4)

In [167]:
data_array.shape

(1134, 5)

In [168]:
CH_array.shape

(1134, 1)

In [149]:
data_array

array([[array([20972, 20387, 18497, 18713, 19180, 13451, 11020, 18902,  5074,
       17418, 16833], dtype=int64),
        0, 0, 1, 3],
       [array([20972, 20387, 18497, 18713, 19180, 13451, 11020, 18902,  5074,
       17418, 16833], dtype=int64),
        1, 0, 3, 1],
       [array([20972, 20387, 18497, 18713, 19180, 13451, 11020, 18902,  5074,
       17418, 16833], dtype=int64),
        1, 0, 3, 1],
       ...,
       [array([20972, 20387, 18497, 18713, 19180, 13451, 11020, 18902,  5074,
       17418, 16833], dtype=int64),
        1, 0, 3, 1],
       [array([20972, 20387, 18497, 18713, 19180, 13451, 11020, 18902,  5074,
       17418, 16833], dtype=int64),
        1, 0, 3, 1],
       [array([20972, 20387, 18497, 18713, 19180, 13451, 11020, 18902,  5074,
       17418, 16833], dtype=int64),
        1, 0, 3, 1]], dtype=object)

In [150]:
CH_array

array([[5.04285714],
       [5.38571429],
       [6.45714286],
       ...,
       [5.2       ],
       [5.6       ],
       [6.66666667]])

In [151]:
np.savetxt("./input_array.txt",data_array,fmt = "%s")

In [152]:
np.savetxt("./CH_array.txt",CH_array,fmt = "%s")

In [10]:
all_data_2[(all_data_2["name"]=="知内川沖") & (all_data_2["Time"] == pd.to_datetime(str(20170629)))].values

array([[439, Timestamp('2017-06-29 00:00:00'), '知内川沖', 35.450881,
        136.065759, 'B1.TIF', 22966, 1, 0, 3, 1, 3.12],
       [440, Timestamp('2017-06-29 00:00:00'), '知内川沖', 35.450881,
        136.065759, 'B2.TIF', 22459, 1, 0, 3, 1, 3.12],
       [441, Timestamp('2017-06-29 00:00:00'), '知内川沖', 35.450881,
        136.065759, 'B3.TIF', 20315, 1, 0, 3, 1, 3.12],
       [442, Timestamp('2017-06-29 00:00:00'), '知内川沖', 35.450881,
        136.065759, 'B4.TIF', 20177, 1, 0, 3, 1, 3.12],
       [443, Timestamp('2017-06-29 00:00:00'), '知内川沖', 35.450881,
        136.065759, 'B5.TIF', 24104, 1, 0, 3, 1, 3.12],
       [444, Timestamp('2017-06-29 00:00:00'), '知内川沖', 35.450881,
        136.065759, 'B6.TIF', 18704, 1, 0, 3, 1, 3.12],
       [445, Timestamp('2017-06-29 00:00:00'), '知内川沖', 35.450881,
        136.065759, 'B7.TIF', 16747, 1, 0, 3, 1, 3.12],
       [446, Timestamp('2017-06-29 00:00:00'), '知内川沖', 35.450881,
        136.065759, 'B8.TIF', 20536, 1, 0, 3, 1, 3.12],
       [447, Timestamp('