In [159]:
import pandas as pd
import numpy as np


all_data = pd.read_excel("./all_data2.xlsx")
all_data.head()

Unnamed: 0       Time name       lon         lat    band  pixel  cloud  \
0           0 2017-03-25  姉川沖  35.38681  136.212837  B1.TIF  10118      0   
1           1 2017-03-25  姉川沖  35.38681  136.212837  B2.TIF   9102      0   
2           2 2017-03-25  姉川沖  35.38681  136.212837  B3.TIF   7809      0   
3           3 2017-03-25  姉川沖  35.38681  136.212837  B4.TIF   7083      0   
4           4 2017-03-25  姉川沖  35.38681  136.212837  B5.TIF   6610      0   

   terrian  cloudconfidence  cloudshade  CH_value  
0        0                1           3  5.042857  
1        0                1           3  5.042857  
2        0                1           3  5.042857  
3        0                1           3  5.042857  
4        0                1           3  5.042857

In [160]:
all_data.dtypes

Unnamed: 0                  int64
Time               datetime64[ns]
name                       object
lon                       float64
lat                       float64
band                       object
pixel                       int64
cloud                       int64
terrian                     int64
cloudconfidence             int64
cloudshade                  int64
CH_value                  float64
dtype: object

In [161]:
all_data.isnull().sum()

Unnamed: 0          0
Time                0
name                0
lon                 0
lat                 0
band                0
pixel               0
cloud               0
terrian             0
cloudconfidence     0
cloudshade          0
CH_value           22
dtype: int64

In [162]:
all_data.shape

(12583, 12)

In [163]:
all_data_2 = all_data.dropna()

In [164]:
all_data_2.shape

(12561, 12)

In [183]:
all_data_2.isnull().sum()

Unnamed: 0         0
Time               0
name               0
lon                0
lat                0
band               0
pixel              0
cloud              0
terrian            0
cloudconfidence    0
cloudshade         0
CH_value           0
dtype: int64

In [166]:
all_data_2.to_excel("./all_data2_nonull.xlsx")

In [167]:
all_data_2

Unnamed: 0       Time    name        lon         lat     band  pixel  \
0               0 2017-03-25     姉川沖  35.386810  136.212837   B1.TIF  10118   
1               1 2017-03-25     姉川沖  35.386810  136.212837   B2.TIF   9102   
2               2 2017-03-25     姉川沖  35.386810  136.212837   B3.TIF   7809   
3               3 2017-03-25     姉川沖  35.386810  136.212837   B4.TIF   7083   
4               4 2017-03-25     姉川沖  35.386810  136.212837   B5.TIF   6610   
...           ...        ...     ...        ...         ...      ...    ...   
12578       12578 2017-02-14  大宮川沖中央  35.056558  135.900578   B7.TIF  16795   
12579       12579 2017-02-14  大宮川沖中央  35.056558  135.900578   B8.TIF  24580   
12580       12580 2017-02-14  大宮川沖中央  35.056558  135.900578   B9.TIF   5217   
12581       12581 2017-02-14  大宮川沖中央  35.056558  135.900578  B10.TIF  15364   
12582       12582 2017-02-14  大宮川沖中央  35.056558  135.900578  B11.TIF  15132   

       cloud  terrian  cloudconfidence  cloudshade  CH_value  
0          0        0                1           3  5.042857  
1          0        0                1           3  5.042857  
2          0        0                1           3  5.042857  
3          0        0                1           3  5.042857  
4          0        0                1           3  5.042857  
...      ...      ...              ...         ...       ...  
12578      1        0                3           1  5.600000  
12579      1        0                3           1  5.600000  
12580      1        0                3           1  5.600000  
12581      1        0                3           1  5.600000  
12582      1        0                3           1  5.600000  

[12561 rows x 12 columns]

In [168]:
len(all_data_2["CH_value"].unique())

883

In [169]:
len(all_data_2["CH_value"])/11

1141.909090909091

In [170]:
np.unique(all_data_2["CH_value"],return_counts = True)

(array([ 1.075     ,  1.125     ,  1.15      ,  1.22857143,  1.25714286,
         1.34285714,  1.35      ,  1.4       ,  1.425     ,  1.42857143,
         1.44285714,  1.45714286,  1.48      ,  1.48571429,  1.5       ,
         1.51428571,  1.525     ,  1.54285714,  1.55      ,  1.575     ,
         1.58571429,  1.6       ,  1.62      ,  1.64      ,  1.65      ,
         1.65714286,  1.675     ,  1.68      ,  1.68571429,  1.7       ,
         1.71428571,  1.725     ,  1.72857143,  1.74285714,  1.75714286,
         1.76      ,  1.77142857,  1.775     ,  1.8       ,  1.86      ,
         1.86666667,  1.87142857,  1.9       ,  1.92      ,  1.92857143,
         1.94285714,  1.95714286,  1.97142857,  1.98571429,  2.        ,
         2.01428571,  2.03333333,  2.03333333,  2.0375    ,  2.04      ,
         2.04285714,  2.05714286,  2.1       ,  2.14      ,  2.14285714,
         2.15      ,  2.16666667,  2.17142857,  2.18571429,  2.18571429,
         2.2       ,  2.22      ,  2.22857143,  2.2

In [171]:
all_data_2[(all_data_2["name"] == "姉川沖") & (all_data_2["Time"] == pd.to_datetime(str(20170325)))]

Unnamed: 0       Time name       lon         lat     band  pixel  cloud  \
0            0 2017-03-25  姉川沖  35.38681  136.212837   B1.TIF  10118      0   
1            1 2017-03-25  姉川沖  35.38681  136.212837   B2.TIF   9102      0   
2            2 2017-03-25  姉川沖  35.38681  136.212837   B3.TIF   7809      0   
3            3 2017-03-25  姉川沖  35.38681  136.212837   B4.TIF   7083      0   
4            4 2017-03-25  姉川沖  35.38681  136.212837   B5.TIF   6610      0   
5            5 2017-03-25  姉川沖  35.38681  136.212837   B6.TIF   5867      0   
6            6 2017-03-25  姉川沖  35.38681  136.212837   B7.TIF   5663      0   
7            7 2017-03-25  姉川沖  35.38681  136.212837   B8.TIF   7467      0   
8            8 2017-03-25  姉川沖  35.38681  136.212837   B9.TIF   5282      0   
9            9 2017-03-25  姉川沖  35.38681  136.212837  B10.TIF  19818      0   
10          10 2017-03-25  姉川沖  35.38681  136.212837  B11.TIF  18751      0   

    terrian  cloudconfidence  cloudshade  CH_value  
0         0                1           3  5.042857  
1         0                1           3  5.042857  
2         0                1           3  5.042857  
3         0                1           3  5.042857  
4         0                1           3  5.042857  
5         0                1           3  5.042857  
6         0                1           3  5.042857  
7         0                1           3  5.042857  
8         0                1           3  5.042857  
9         0                1           3  5.042857  
10        0                1           3  5.042857

In [86]:
pd.to_datetime(20170325)

Timestamp('1970-01-01 00:00:00.020170325')

In [87]:
all_data_2[(all_data_2["name"] == "姉川沖") & (all_data_2["Time"] == pd.to_datetime(str(20170325)))]["pixel"].values

array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64)

In [172]:
time = []
time = all_data_2["Time"].unique()
print(time)

['2017-03-25T00:00:00.000000000' '2017-03-09T00:00:00.000000000'
 '2017-05-12T00:00:00.000000000' '2017-05-28T00:00:00.000000000'
 '2017-06-13T00:00:00.000000000' '2017-06-29T00:00:00.000000000'
 '2017-07-15T00:00:00.000000000' '2017-07-31T00:00:00.000000000'
 '2017-08-16T00:00:00.000000000' '2017-09-01T00:00:00.000000000'
 '2017-11-04T00:00:00.000000000' '2017-11-20T00:00:00.000000000'
 '2017-12-06T00:00:00.000000000' '2017-12-22T00:00:00.000000000'
 '2018-01-07T00:00:00.000000000' '2018-01-23T00:00:00.000000000'
 '2018-02-08T00:00:00.000000000' '2018-02-24T00:00:00.000000000'
 '2018-03-12T00:00:00.000000000' '2018-03-28T00:00:00.000000000'
 '2018-04-13T00:00:00.000000000' '2018-04-29T00:00:00.000000000'
 '2018-05-15T00:00:00.000000000' '2018-06-16T00:00:00.000000000'
 '2018-07-02T00:00:00.000000000' '2018-07-18T00:00:00.000000000'
 '2018-08-03T00:00:00.000000000' '2018-08-19T00:00:00.000000000'
 '2018-09-04T00:00:00.000000000' '2018-10-06T00:00:00.000000000'
 '2018-10-22T00:00:00.000

In [173]:
kyoten = []
kyoten = all_data_2["name"].unique()
kyoten

array(['姉川沖', '天野川沖', '彦根港沖', '蓮菜沖', '日の川沖', '大宮川沖', '大宮川沖中央', '知内川沖'],
      dtype=object)

In [91]:
all_data_2[(all_data_2["name"] == "姉川沖") & (all_data_2["Time"] == pd.to_datetime(str(20170325)))]["pixel"].values

array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64)

In [107]:
list = []
list2 = []
pixel = []
for x in range(0,883):
    for t,n in zip(time,kyoten):
        pixel = all_data_2["pixel"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        CH = all_data_2["CH_value"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
    #print(CH)
        list += [x,n,t,pixel,CH[0]]
        list2 += [[x,pixel,CH[0]]]
    
#print(list)   

#array = np.array(list)
#rray
array2 = np.array(list2)
array2

array([[0,
        array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        5.042857142857143],
       [0,
        array([10704,  9643,  8168,  7285,  6552,  5697,  5511,  7888,  5043,
       19176, 18279], dtype=int64),
        4.842857142857143],
       [0,
        array([12516, 11451,  9997,  8853,  8596,  7301,  6807,  9659,  5618,
       22082, 20322], dtype=int64),
        9.6],
       ...,
       [882,
        array([20130, 19039, 17816, 17245, 20017, 14496, 13045, 17530,  7646,
       13586, 13006, 20130, 19039, 17816, 17245, 20017, 14496, 13045,
       17530,  7646, 13586, 13006], dtype=int64),
        9.366666666666667],
       [882,
        array([12019, 10808,  9895,  8670,  8132,  7789,  7067,  8938,  5483,
       24090, 22235], dtype=int64),
        5.328571428571428],
       [882,
        array([12578, 11415,  9798,  8698,  8733,  7447,  6767,  9440,  5030,
       26245, 23524], dtype=int64),
        1.8]], dtype=o

In [93]:
all_data_2[(all_data_2["name"]== "知内川沖") & (all_data_2["Time"]== pd.to_datetime(str(20170731)))]["pixel"].values

array([12578, 11415,  9798,  8698,  8733,  7447,  6767,  9440,  5030,
       26245, 23524], dtype=int64)

In [94]:
all_data_2[(all_data_2["name"] == "知内川沖") & (all_data_2["Time"] == pd.to_datetime(str(20170731)))]["CH_value"].values

array([1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8])

In [70]:
#np.savetxt("./data_array.txt",array2,fmt = "%s")

In [99]:
print(array2)

[0
 array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64)
 5.042857142857143 ... 882
 array([12578, 11415,  9798,  8698,  8733,  7447,  6767,  9440,  5030,
       26245, 23524], dtype=int64)
 1.8]


In [108]:
array2.shape

(7064, 3)

In [111]:
array3 = np.delete(array2,0,1)

In [112]:
array3


array([[array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        5.042857142857143],
       [array([10704,  9643,  8168,  7285,  6552,  5697,  5511,  7888,  5043,
       19176, 18279], dtype=int64),
        4.842857142857143],
       [array([12516, 11451,  9997,  8853,  8596,  7301,  6807,  9659,  5618,
       22082, 20322], dtype=int64),
        9.6],
       ...,
       [array([20130, 19039, 17816, 17245, 20017, 14496, 13045, 17530,  7646,
       13586, 13006, 20130, 19039, 17816, 17245, 20017, 14496, 13045,
       17530,  7646, 13586, 13006], dtype=int64),
        9.366666666666667],
       [array([12019, 10808,  9895,  8670,  8132,  7789,  7067,  8938,  5483,
       24090, 22235], dtype=int64),
        5.328571428571428],
       [array([12578, 11415,  9798,  8698,  8733,  7447,  6767,  9440,  5030,
       26245, 23524], dtype=int64),
        1.8]], dtype=object)

In [115]:
array3.shape

(7064, 2)

In [122]:
def get_unique_list(seq):
    seen = []
    for x in seq:
        if x not in seen:
            seen.append(x)
    return seen

In [123]:
array4 = get_unique_list(array3)

C:\Users\meina\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  after removing the cwd from sys.path.


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [176]:
list = []
list3 = []
pixel = []

for t,n in zip(time,kyoten):
    for x in range(0,1142):
        pixel = all_data_2["pixel"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        CH = all_data_2["CH_value"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
    #print(CH)
        list += [x,n,t,pixel,CH[0]]
        list3 += [[x,pixel,CH[0]]]
    
#print(list)   

#array = np.array(list)
#rray
array5 = np.array(list3)
array5

array([[0,
        array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        5.042857142857143],
       [1,
        array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        5.042857142857143],
       [2,
        array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        5.042857142857143],
       ...,
       [1139,
        array([12578, 11415,  9798,  8698,  8733,  7447,  6767,  9440,  5030,
       26245, 23524], dtype=int64),
        1.8],
       [1140,
        array([12578, 11415,  9798,  8698,  8733,  7447,  6767,  9440,  5030,
       26245, 23524], dtype=int64),
        1.8],
       [1141,
        array([12578, 11415,  9798,  8698,  8733,  7447,  6767,  9440,  5030,
       26245, 23524], dtype=int64),
        1.8]], dtype=object)

In [139]:
#np.savetxt("./data_array_test1.txt",array5,fmt = "%s")

In [175]:
list4 = []
pixel2 = []
for t,n in zip(time,kyoten):
    pixel = all_data_2["pixel"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
    CH = all_data_2["CH_value"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
    #print(CH)
    list4 += [[n,pixel,CH[0]]]
    
#print(list)   

#array = np.array(list)
#rray
array6 = np.array(list2)
array6

array([[0,
        array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        5.042857142857143],
       [0,
        array([10704,  9643,  8168,  7285,  6552,  5697,  5511,  7888,  5043,
       19176, 18279], dtype=int64),
        4.842857142857143],
       [0,
        array([12516, 11451,  9997,  8853,  8596,  7301,  6807,  9659,  5618,
       22082, 20322], dtype=int64),
        9.6],
       ...,
       [882,
        array([20130, 19039, 17816, 17245, 20017, 14496, 13045, 17530,  7646,
       13586, 13006, 20130, 19039, 17816, 17245, 20017, 14496, 13045,
       17530,  7646, 13586, 13006], dtype=int64),
        9.366666666666667],
       [882,
        array([12019, 10808,  9895,  8670,  8132,  7789,  7067,  8938,  5483,
       24090, 22235], dtype=int64),
        5.328571428571428],
       [882,
        array([12578, 11415,  9798,  8698,  8733,  7447,  6767,  9440,  5030,
       26245, 23524], dtype=int64),
        1.8]], dtype=o

In [141]:
#np.savetxt("./data_array_test2.txt",array6,fmt = "%s")

In [188]:
list5 = []
pixel3 = []
CH1 = []
for t in time:
    for n in kyoten:
        pixel3 = all_data_2["pixel"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        CH1 = all_data_2["CH_value"][(all_data_2["Time"] == t) & (all_data_2["name"] == n)].values
        #print(CH1)
        if len(CH1) != 0:
            list5 += [[t,n,pixel3,CH1[0]]]
    
#print(list)   

#array = np.array(list)
#rray
array7 = np.array(list5)
array7

array([[numpy.datetime64('2017-03-25T00:00:00.000000000'), '姉川沖',
        array([10118,  9102,  7809,  7083,  6610,  5867,  5663,  7467,  5282,
       19818, 18751], dtype=int64),
        5.042857142857143],
       [numpy.datetime64('2017-03-25T00:00:00.000000000'), '天野川沖',
        array([11505, 10443,  9137,  8595,  8440,  6879,  6622,  8891,  5832,
       18872, 18048], dtype=int64),
        5.385714285714286],
       [numpy.datetime64('2017-03-25T00:00:00.000000000'), '彦根港沖',
        array([11487, 10326,  9673,  8788,  8332,  7186,  6848,  8808,  5877,
       18721, 17630], dtype=int64),
        6.457142857142857],
       ...,
       [numpy.datetime64('2017-02-14T00:00:00.000000000'), '大宮川沖',
        array([16478, 15578, 13855, 13575, 13946, 10502,  9527, 13877,  5074,
       16827, 16272], dtype=int64),
        5.2],
       [numpy.datetime64('2017-02-14T00:00:00.000000000'), '大宮川沖中央',
        array([25701, 25632, 24003, 24956, 26335, 19614, 16795, 24580,  5217,
       15364, 15132]

In [194]:
np.savetxt("./data_array_dekita.txt",array7,fmt = "%s")

In [190]:
array7.shape

(1134, 4)

In [191]:
all_data_2[(all_data_2["name"]== "知内川沖") & (all_data_2["Time"]== pd.to_datetime(str(20170214)))]["pixel"].values

array([20972, 20387, 18497, 18713, 19180, 13451, 11020, 18902,  5074,
       17418, 16833], dtype=int64)

In [193]:
all_data_2[(all_data_2["name"]== "知内川沖") & (all_data_2["Time"]== pd.to_datetime(str(20170214)))]["CH_value"].values

array([6.66666667, 6.66666667, 6.66666667, 6.66666667, 6.66666667,
       6.66666667, 6.66666667, 6.66666667, 6.66666667, 6.66666667,
       6.66666667])