In [12]:
import rasterio as rio
import pyproj
import numpy as np
B5 = rio.open("./TOA/LC08_L1TP_110035_20160728_20170322_01_T1_B1.tiff")

B5

B5.meta

#use pyproj to onvert poit coordinates
utm = pyproj.Proj(B5.crs)
lonlat = pyproj.Proj(init='epsg:4326')
lat,lon = (35.450881,136.065759)
east,north = pyproj.transform(lonlat,utm,lon,lat)

east,north

utm

#Datasets have an index() method for getting the array indices corresponding to points in georeferenced space. 
row, col = B5.index(east,north)

#print(f'row,col=\t\t({row},{col})')

B5.indexes

#Data from a raster band can be accessed by the band’s index number.
B5read = B5.read(1)
B5read

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint16)

In [14]:
print(B5read[row,col])

#周り9点を読み込む
print(B5read[row-1:row+2,col-1:col+2])
print(np.mean(B5read[row-1:row+2,col-1:col+2]))
DNmean = np.mean(B5read[row-1:row+2,col-1:col+2])
#Returns the coordinates (x, y) of a pixel at row and col.
#B5.xy(row-1,col-1)

35027
[[36648 36127 35164]
 [35744 35027 35173]
 [36192 35117 35603]]
35643.88888888889


In [16]:
with open("./TOA/meta.txt") as f:
    lines = f.readlines()

In [18]:
print(lines)

['GROUP = L1_METADATA_FILE\n', '  GROUP = METADATA_FILE_INFO\n', '    ORIGIN = "Image courtesy of the U.S. Geological Survey"\n', '    REQUEST_ID = "0501703221595_00002"\n', '    LANDSAT_SCENE_ID = "LC81100352016210LGN01"\n', '    LANDSAT_PRODUCT_ID = "LC08_L1TP_110035_20160728_20170322_01_T1"\n', '    COLLECTION_NUMBER = 01\n', '    FILE_DATE = 2017-03-22T18:50:10Z\n', '    STATION_ID = "LGN"\n', '    PROCESSING_SOFTWARE_VERSION = "LPGS_2.7.0"\n', '  END_GROUP = METADATA_FILE_INFO\n', '  GROUP = PRODUCT_METADATA\n', '    DATA_TYPE = "L1TP"\n', '    COLLECTION_CATEGORY = "T1"\n', '    ELEVATION_SOURCE = "GLS2000"\n', '    OUTPUT_FORMAT = "GEOTIFF"\n', '    SPACECRAFT_ID = "LANDSAT_8"\n', '    SENSOR_ID = "OLI_TIRS"\n', '    WRS_PATH = 110\n', '    WRS_ROW = 35\n', '    NADIR_OFFNADIR = "NADIR"\n', '    TARGET_WRS_PATH = 110\n', '    TARGET_WRS_ROW = 35\n', '    DATE_ACQUIRED = 2016-07-28\n', '    SCENE_CENTER_TIME = "01:34:22.6581130Z"\n', '    CORNER_UL_LAT_PRODUCT = 37.09322\n', '   

In [19]:
lines_strip = [line.strip() for line in lines]

In [20]:
print(lines_strip)

['GROUP = L1_METADATA_FILE', 'GROUP = METADATA_FILE_INFO', 'ORIGIN = "Image courtesy of the U.S. Geological Survey"', 'REQUEST_ID = "0501703221595_00002"', 'LANDSAT_SCENE_ID = "LC81100352016210LGN01"', 'LANDSAT_PRODUCT_ID = "LC08_L1TP_110035_20160728_20170322_01_T1"', 'COLLECTION_NUMBER = 01', 'FILE_DATE = 2017-03-22T18:50:10Z', 'STATION_ID = "LGN"', 'PROCESSING_SOFTWARE_VERSION = "LPGS_2.7.0"', 'END_GROUP = METADATA_FILE_INFO', 'GROUP = PRODUCT_METADATA', 'DATA_TYPE = "L1TP"', 'COLLECTION_CATEGORY = "T1"', 'ELEVATION_SOURCE = "GLS2000"', 'OUTPUT_FORMAT = "GEOTIFF"', 'SPACECRAFT_ID = "LANDSAT_8"', 'SENSOR_ID = "OLI_TIRS"', 'WRS_PATH = 110', 'WRS_ROW = 35', 'NADIR_OFFNADIR = "NADIR"', 'TARGET_WRS_PATH = 110', 'TARGET_WRS_ROW = 35', 'DATE_ACQUIRED = 2016-07-28', 'SCENE_CENTER_TIME = "01:34:22.6581130Z"', 'CORNER_UL_LAT_PRODUCT = 37.09322', 'CORNER_UL_LON_PRODUCT = 134.21794', 'CORNER_UR_LAT_PRODUCT = 37.08204', 'CORNER_UR_LON_PRODUCT = 136.80684', 'CORNER_LL_LAT_PRODUCT = 34.98099', 'COR

In [43]:
l_meta = [line for line in lines_strip if 'RADIANCE_MULT_BAND_1 =' in line]
l_add = [line for line in lines_strip if "RADIANCE_ADD_BAND_1 =" in line]

In [44]:
print(l_meta)

['RADIANCE_MULT_BAND_1 = 1.2177E-02']


In [45]:
print(l_add)

['RADIANCE_ADD_BAND_1 = -60.88470']


In [50]:
l_meta2 =[ i.split("=") for i in l_meta]
print(l_meta2)
l_meta3 = float(l_meta2[0][1])
print(l_meta3)

[['RADIANCE_MULT_BAND_1 ', ' 1.2177E-02']]
0.012177


In [51]:
l_add2 = [i.split("=") for i in l_add]
print(l_add2)
l_add3 = float(l_add2[0][1])
print(l_add3)

[['RADIANCE_ADD_BAND_1 ', ' -60.88470']]
-60.8847


In [52]:
R = DNmean*l_meta3 + l_add3

In [53]:
print(R)

373.150935
